---

- name: Start the MySQL service
  sudo: yes
  service: 
    name: mysql 
    state: started
    enabled: true

- name: update mysql root password for all root accounts
  sudo: yes
  mysql_user: 
    name: "{{ mysql_user }}"
    host: "{{ item }}" 
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost 

- template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    mode: 0600

- name: remove default database 
  mysql_db:
    name: test
    state: absent
   # login_unix_socket: /var/run/mysqld/mysqld.sock 
