---

- name: Install PHP CLI
  apt:
    name: "{{ item }}"
    state: present
  with_items: 
  - php-pear 
  - php-fpm 
  - php-dev 
  - php-zip
  - php-curl 
  - php-xmlrpc 
  - php-gd 
  - php-mysql 
  - php-mbstring 
  - php-xml 
  - libapache2-mod-php